### ISSUE TITLE
name issue & colour scalebar fails

### ISSUE THREAD

**Issue by mmetois** [BC-Consulting/geoprocalgos#1]
Thank you for making these tools compatible with QGIS 3.x ! I am a user of the colour scalebar tool but I ran into several problems when running it on standard grdfiles : 
- first : by default, ~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/res/bcCbar.svg should be ~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/res/bcCBar.svg otherwise it crashes. 
- once this solved, the tool fails in getting a colour bar. Here are the outputs inside QGIS :

> QGIS version: 3.6.3-Noosa
> QGIS code revision: 0c5774c
> Qt version: 5.9.5
> GDAL version: 2.4.0
> GEOS version: 3.7.0-CAPI-1.11.0 673b9939
> PROJ version: 520
> Traitement de l'algorithme…
> Démarrage de l'algorithme 'Create Colour Scalebar'…
> Paramètres en entrée:
> { 'BORDER_COLOR' : 'black', 'BORDER_LW' : 1, 'BREVERSED' : False, 'CBWH' : 0.1, 'DECI' : 2, 'DIVIDER_COLOR' : 'black', 'DIVIDER_LW' : 0, 'FONT_SIZE' : 4, 'LABEL_ALT' : False, 'LABEL_BOTH' : False, 'LABEL_ON' : 0, 'OFFSET' : 0, 'ORI' : 0, 'OUTPUT' : '/home/marianne/.local/share/QGIS/QGIS3/profiles/default/processing/outputs/cb.svg', 'TFONT' : 2, 'THE_LAYER' : '/home/marianne/BOULOT/LABO/formation_qgis/test.nc', 'TICKSEP' : 1, 'TITLE' : '', 'TITLE_COLOR' : 'black', 'UFONT' : 1, 'UNITS' : '', 'UNITS_COLOR' : 'black', 'WITH_PNG' : False, 'XTRA_PARAM' : '' }
> 
> Traceback (most recent call last):
> File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/bcCBar_algorithm.py", line 442, in processAlgorithm
> output_file = self._continue_proc(mycb, ori, labboth, labalt, output_file)
> File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/bcCBar_algorithm.py", line 254, in _continue_proc
> if mycb.draw_cb():
> File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/CBar3.py", line 1094, in draw_cb
> ym = self._set_units(' ', cax, fontu) * twk
> File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/CBar3.py", line 697, in _set_units
> pad=pad)
> File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 189, in set_title
> title.update(kwargs)
> File "/usr/lib/python3/dist-packages/matplotlib/text.py", line 192, in update
> super(Text, self).update(kwargs)
> File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 902, in update
> for k, v in props.items()]
> File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 902, in <listcomp>
> for k, v in props.items()]
> File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 895, in _update_property
> raise AttributeError('Unknown property %s' % k)
> AttributeError: Unknown property pad
> 
> Échec d'exécution au bout de 0.55 secondes

Terminal output : 

>   File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/bcCBar_algorithm.py", line 442, in processAlgorithm
>     output_file = self._continue_proc(mycb, ori, labboth, labalt, output_file)
>   File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/bcCBar_algorithm.py", line 254, in _continue_proc
>     if mycb.draw_cb():
>   File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/CBar3.py", line 1094, in draw_cb
>     ym = self._set_units(' ', cax, fontu) * twk
>   File "/home/marianne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/CBar3.py", line 697, in _set_units
>     pad=pad)
>   File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 189, in set_title
>     title.update(kwargs)
>   File "/usr/lib/python3/dist-packages/matplotlib/text.py", line 192, in update
>     super(Text, self).update(kwargs)
>   File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 902, in update
>     for k, v in props.items()]
>   File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 902, in <listcomp>
>     for k, v in props.items()]
>   File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 895, in _update_property
>     raise AttributeError('Unknown property %s' % k)
> AttributeError: Unknown property pad

I am running Ubuntu 18.04 and QGIS 3.6
Thank you,
M.

**Comment by BC-Consulting** [comment]
Bonjour M,

Nice to see you are (trying) to use GeoProcAlgos!

Question 1: In fact it is mostly due to how I defined paths. I've changed that for the upcoming update.

Question 2: Can you please tell me what is your matplotlib version? My system has 3.0.0.
I suspect yours to be a 2.x, in such a case the "pad" parameter does not exist. If this is the case, you should probably update your version of matplotlib and I need to update the requirements to add minimum matplotlib version.

Hope this helps!
Cheers,
Benoit

**Comment by mmetois** [comment]
HI Benoit, 
You were right about matplolib version, after upgrading to matplotlib3 via a dirty
`sudo pip install matplotlib3`
it works fine. 
Thanks again for your quick answer
Marianne

**Comment by BC-Consulting** [comment]
Only a pleasure...
