### ISSUE TITLE
Geoproc tools not available after updating to the 3.14 version

### ISSUE THREAD

**Issue by AlbaMat** [BC-Consulting/geoprocalgos#3]
Hello.
After upgrading the Geoprocalgos plugin to the 3.14 version, a python error appeared and the menu is no longer available in the processing menu.
My QGIS version is 3.10.9 64bit running on WIN10

Thank you

**Comment by BC-Consulting** [comment]
Good day Matteo,
    Many thanks for reporting the error.
    Could I ask you to please send me the error message you've
      received so that I can find the bug?
    Thanks,
      Benoit
    
    
    On 10/09/2020 16:45, Matteo Albano
      wrote:
    
    
      
      Hello.
        After upgrading the Geoprocalgos plugin to the 3.14 version, a
        python error appeared and the menu is no longer available in the
        processing menu.
        My QGIS version is 3.10.9 64bit running on WIN10
      Thank you
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BC-Consulting/geoprocalgos/issues/3",
"url": "https://github.com/BC-Consulting/geoprocalgos/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AlbaMat** [comment]
This is the error:

ModuleNotFoundError: No module named 'geoprocAlgos.QgsBcUtils' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\__init__.py", line 38, in classFactory
    from .GeoProcAlgos import PPlugins
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\GeoProcAlgos.py", line 34, in 
    from .GeoProc_provider import geoprocProvider
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\GeoProc_provider.py", line 33, in 
    from .bcCBar_algorithm             import bcCBarAlgorithm
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\bcCBar_algorithm.py", line 38, in 
    from .QgsBcUtils import check_oneband, save_qml, check_color, check_qml_sidecar
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'geoprocAlgos.QgsBcUtils'


Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.10.9-A Coruña A Coruña, bf47e9d3e1 

Percorso Python:
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TerrainShading
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\ASUS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\ASUS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\ASUS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\ASUS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/ASUS/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timeseriesviewerplugin
C:\Users\ASUS\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\timeseriesviewerplugin\eotimeseriesviewer
C:/Users/ASUS/Desktop/INGV/Lav_Etna/GIS/Progetto

**Comment by BC-Consulting** [comment]
Hi Matteo,

Version 3.15 is up in the repository and should fix the missing module error.

Please note: on my machine I'm obliged to delete the content of the cache at (1) in order for QGIS to see the new version... You could have to do the same!

Best regards,
Benoit

(1): C:\Users\***USERNAME***\AppData\Local\QGIS\QGIS3\cache

**Comment by AlbaMat** [comment]
Now it works! Thank you!
