### ISSUE TITLE
set_ticks() function error

### ISSUE THREAD

**Issue by addisonvantu** [BC-Consulting/geoprocalgos#5]
Hi,

I am receiving this error when I run the Create Colour Bar Function:

![image](https://github.com/BC-Consulting/geoprocalgos/assets/117136890/67d1b338-7b66-4665-a0c9-76edbb80e8cf)

Here's the Log in case that image above doesn't work:

QGIS version: 3.28.3-Firenze
QGIS code revision: 9ae208a46d
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2023-06-14T18:10:34
Algorithm 'Create Colour bar' starting…
Input parameters:
{ 'BREVERSED' : False, 'CLENGTH' : 10, 'CWIDTH' : 0.75, 'DECI' : 2, 'DEDGES' : False, 'FONT_SIZE' : 28, 'LABEL_ALT' : 2, 'LABEL_ON' : 0, 'ORI' : 1, 'OUTPUT' : './cb.svg', 'THE_LAYER' : '/Users/addisontu/Library/CloudStorage/OneDrive-TheUniversityofSydney(Students)/Honours/Thesis/Thermochronology/AFT Cooling Age Compilation/Legend Background.tif', 'TICKCOLO' : '#666666', 'TICKFONTSIZE' : 14, 'TICKLENGTH' : 8, 'TICKSEP' : -5, 'TITLE' : '', 'TITLE_COLOR' : 'k', 'TITLE_FONT' : 1, 'TITLE_WEIGHT' : 4, 'TWK_ADD' : False, 'TWK_REPLACE' : True, 'VERBOSE' : False }

Traceback (most recent call last):
File "/Users/addisontu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/bcCBar_algorithm.py", line 260, in processAlgorithm
if not mycb.createCBar():
File "/Users/addisontu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/cbar/__init__.py", line 810, in createCBar
if self.__doCB():
File "/Users/addisontu/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geoprocAlgos/cbar/__init__.py", line 947, in __doCB
#
TypeError: set_ticks() got an unexpected keyword argument 'labels'

Thanks!

**Comment by BC-Consulting** [comment]
Thanks for reporting this error.
How many colours does your raster have?
And what is its colour range (min-max values)?

**Comment by AddisonTu** [comment]
Just one band and Im using the red-white-blue colour ramp.  Here's an image of the symbology in QGIS, the example is using discrete interpolation but I also tried linear too.

![image](https://github.com/BC-Consulting/geoprocalgos/assets/103798104/3c0d5dbf-152c-49f4-8e06-a3bf5ed389f3)

Thanks for the timely response and appreciate the help!

**Comment by BC-Consulting** [comment]
Hi,

I've tried to replicate the error but it seems fine on my system:
![2-18](https://github.com/BC-Consulting/geoprocalgos/assets/9070651/d91a0124-3a0e-4d27-8765-b04d2f15ea46)

What is the version of the plugin you are using: is it 3.30?

**Comment by addisonvantu** [comment]
Yeah 3.30

**Comment by BC-Consulting** [comment]
OK, thanks.
Could you please send the style file (.qml) created with: right-click on layer name, then "Export -> Save as QGIS Layer Style file..."? (Please use info at geoproc dot com, if it is confidential)
Also, has QGIS write access to the folder containing your raster file?

**Comment by BC-Consulting** [comment]
Other users had the same error. It turned out that their python and matplotlib version were not supported. Please check on your side, and reopen the ticket if it doesn't fix your problem. Thanks.
