### ISSUE TITLE
Multi-Styles fails silently if qml directory does not exist

### ISSUE THREAD

**Issue by AlisterH** [BC-Consulting/geoprocalgos#7]
I tried entering a non-existing "qml directory" when saving, to see if Multi-Styles would create the directory.  It failed silently.
Ideally it would either produce an error message or try to create the directory.

**Comment by AlisterH** [comment]
Well, "silently" in the Log tab of the algorithm dialog.
Worse than silently in the html:
```
Multi-styles operation results on:
D:/New folder/culvert points.shp
Path where .qml's are located: [D:\New folder\testsss](file:///D:/New%20folder/testsss)

Operation: save multi-styles to qml files.
D:\New folder\testsss\default.qml: is saved.
```
`D:\New folder\testsss does not exist`, so that qml is in fact **not** saved.

**Comment by AlisterH** [comment]
Note that there is an error if you try to use a non-existing directory **when loading**:
```
Traceback (most recent call last):
File "C:\Users/alister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geoprocAlgos\bcMultiStyles_algorithm.py", line 217, in processAlgorithm
qml_lst = [f for f in os.listdir(qml_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\New folder\\test1'

Execution failed after 0.03 seconds
```

**Comment by BC-Consulting** [comment]
Thanks Alister for pointing out this bug.
Fixed in upcoming version.
It will save to QGIS temp folder rather than try to create a directory that could, for many reasons, not be created.
